//! Build script for the gateway crate.
//!
//! Reads `predefined/skills/builtin-skills.json` and generates Rust code that embeds all
//! built-in skill files via `include_str!()` with pre-computed blake3 hashes.

use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let skills_root = Path::new(&manifest_dir).join("../../predefined/skills");

    // Read the JSON manifest
    let manifest_path = skills_root.join("builtin-skills.json");
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    let json: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&manifest_path).unwrap())
            .expect("builtin-skills.json is valid JSON");
    let skills = json["skills"].as_array().expect("builtin-skills.json has skills array");

    // Build the output
    let mut out = String::new();

    out.push_str("// Auto-generated by build.rs from predefined/skills/builtin-skills.json.\n");
    out.push_str("// DO NOT EDIT.\n");
    out.push_str("fn builtin_skills() -> Vec<BuiltinSkill> {\n");
    out.push_str("    vec![\n");

    for skill in skills {
        let name = skill["name"].as_str().unwrap();
        out.push_str("        BuiltinSkill {\n");
        out.push_str(&format!("            name: \"{name}\",\n"));
        out.push_str("            files: vec![\n");

        for file in skill["files"].as_array().unwrap() {
            let rel = file.as_str().unwrap();
            let abs_path = skills_root.join(rel);

            // Emit rerun-if-changed so modified files trigger a rebuild
            println!("cargo:rerun-if-changed={}", abs_path.display());

            // Compute blake3 hash of the file content
            let content = std::fs::read_to_string(&abs_path)
                .unwrap_or_else(|e| panic!("failed to read {abs_path:?}: {e}"));
            let hash = blake3::hash(content.as_bytes()).to_hex().to_string();

            // Generate include_str! with a path relative to CARGO_MANIFEST_DIR
            out.push_str(&format!(
                "                (\n                    \"{rel}\",\n                    \"{hash}\",\n                    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../predefined/skills/{rel}\")),\n                ),\n"
            ));
        }

        out.push_str("            ],\n");
        out.push_str("        },\n");
    }

    out.push_str("    ]\n");
    out.push_str("}\n");

    // Write the generated file
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("builtin_skills.rs");
    std::fs::write(&dest, out).unwrap();
}
