// Copyright (c) 2026 13F
// SPDX-License-Identifier: AGPL-3.0

//! Build script for the gateway crate.
//!
//! Reads `predefined/skills/builtin-skills.json` and `predefined/plugins/builtin-plugins.json`
//! and generates Rust code that embeds all built-in files via `include_str!()` with
//! pre-computed blake3 hashes.

use std::path::Path;

fn main() {
    // Compile proto definitions for gRPC server stubs.
    tonic_build::compile_protos("../../proto/aman.proto")
        .expect("failed to compile aman.proto");

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let predefined_root = Path::new(&manifest_dir).join("../../predefined");
    let skills_root = predefined_root.join("skills");
    let plugins_root = predefined_root.join("plugins");

    // -----------------------------------------------------------------------
    // Skills
    // -----------------------------------------------------------------------
    let skills_manifest_path = skills_root.join("builtin-skills.json");
    println!("cargo:rerun-if-changed={}", skills_manifest_path.display());
    let skills_json: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&skills_manifest_path).unwrap())
            .expect("builtin-skills.json is valid JSON");
    let skills = skills_json["skills"].as_array().expect("builtin-skills.json has skills array");

    let mut skills_out = String::new();
    skills_out.push_str("// Auto-generated by build.rs from predefined/skills/builtin-skills.json.\n");
    skills_out.push_str("// DO NOT EDIT.\n");
    skills_out.push_str("fn builtin_skills() -> Vec<BuiltinSkill> {\n");
    skills_out.push_str("    vec![\n");

    for skill in skills {
        let name = skill["name"].as_str().unwrap();
        skills_out.push_str("        BuiltinSkill {\n");
        skills_out.push_str(&format!("            name: \"{name}\",\n"));
        skills_out.push_str("            files: vec![\n");

        for file in skill["files"].as_array().unwrap() {
            let rel = file.as_str().unwrap();
            let abs_path = skills_root.join(rel);

            println!("cargo:rerun-if-changed={}", abs_path.display());

            let content = std::fs::read_to_string(&abs_path)
                .unwrap_or_else(|e| panic!("failed to read {abs_path:?}: {e}"));
            let hash = blake3::hash(content.as_bytes()).to_hex().to_string();

            skills_out.push_str(&format!(
                "                (\n                    \"{rel}\",\n                    \"{hash}\",\n                    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../predefined/skills/{rel}\")),\n                ),\n"
            ));
        }

        skills_out.push_str("            ],\n");
        skills_out.push_str("        },\n");
    }

    skills_out.push_str("    ]\n");
    skills_out.push_str("}\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let skills_dest = Path::new(&out_dir).join("builtin_skills.rs");
    std::fs::write(&skills_dest, skills_out).unwrap();

    // -----------------------------------------------------------------------
    // Plugins
    // -----------------------------------------------------------------------
    let plugins_manifest_path = plugins_root.join("builtin-plugins.json");
    println!("cargo:rerun-if-changed={}", plugins_manifest_path.display());
    let plugins_json: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&plugins_manifest_path).unwrap())
            .expect("builtin-plugins.json is valid JSON");
    let plugins = plugins_json["plugins"].as_array().expect("builtin-plugins.json has plugins array");

    let mut plugins_out = String::new();
    plugins_out.push_str("// Auto-generated by build.rs from predefined/plugins/builtin-plugins.json.\n");
    plugins_out.push_str("// DO NOT EDIT.\n");
    plugins_out.push_str("fn builtin_plugins() -> Vec<BuiltinPlugin> {\n");
    plugins_out.push_str("    vec![\n");

    for plugin in plugins {
        let name = plugin["name"].as_str().unwrap();
        plugins_out.push_str("        BuiltinPlugin {\n");
        plugins_out.push_str(&format!("            name: \"{name}\",\n"));
        plugins_out.push_str("            files: vec![\n");

        for file in plugin["files"].as_array().unwrap() {
            let rel = file.as_str().unwrap();
            let abs_path = plugins_root.join(rel);

            println!("cargo:rerun-if-changed={}", abs_path.display());

            let content = std::fs::read_to_string(&abs_path)
                .unwrap_or_else(|e| panic!("failed to read {abs_path:?}: {e}"));
            let hash = blake3::hash(content.as_bytes()).to_hex().to_string();

            plugins_out.push_str(&format!(
                "                (\n                    \"{rel}\",\n                    \"{hash}\",\n                    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../predefined/plugins/{rel}\")),\n                ),\n"
            ));
        }

        plugins_out.push_str("            ],\n");
        plugins_out.push_str("        },\n");
    }

    plugins_out.push_str("    ]\n");
    plugins_out.push_str("}\n");

    let plugins_dest = Path::new(&out_dir).join("builtin_plugins.rs");
    std::fs::write(&plugins_dest, plugins_out).unwrap();
}
