// Copyright (c) 2026 13F
// SPDX-License-Identifier: AGPL-3.0

//! Build script for the gateway crate.
//!
//! Reads `predefined/builtin.json` as the top-level index, then follows its
//! `skills` and `plugins` pointers to discover and embed all built-in files
//! via `include_str!()` with pre-computed blake3 hashes.

use std::path::Path;

fn main() {
    // Compile proto definitions for gRPC server stubs.
    tonic_build::compile_protos("../../proto/aman.proto")
        .expect("failed to compile aman.proto");

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let predefined_root = Path::new(&manifest_dir).join("../../predefined");

    // Read the top-level builtin index. All sub-manifest paths are resolved
    // relative to `predefined/`.
    let builtin_path = predefined_root.join("builtin.json");
    println!("cargo:rerun-if-changed={}", builtin_path.display());
    let builtin: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&builtin_path).unwrap())
            .expect("builtin.json is valid JSON");

    // -------------------------------------------------------------------
    // Skills
    // -------------------------------------------------------------------
    if let Some(skills_rel) = builtin["skills"].as_str() {
        let skills_root = predefined_root.join("skills");
        let manifest_path = predefined_root.join(skills_rel);
        println!("cargo:rerun-if-changed={}", manifest_path.display());
        let skills_json: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&manifest_path).unwrap())
                .expect("skills manifest is valid JSON");
        let skills = skills_json["skills"]
            .as_array()
            .expect("skills manifest has skills array");

        let mut out = String::new();
        out.push_str(
            "// Auto-generated by build.rs from predefined/skills/builtin-skills.json.\n",
        );
        out.push_str("// DO NOT EDIT.\n");
        out.push_str("fn builtin_skills() -> Vec<BuiltinSkill> {\n");
        out.push_str("    vec![\n");

        for skill in skills {
            let name = skill["name"].as_str().unwrap();
            out.push_str("        BuiltinSkill {\n");
            out.push_str(&format!("            name: \"{name}\",\n"));
            out.push_str("            files: vec![\n");

            for file in skill["files"].as_array().unwrap() {
                let rel = file.as_str().unwrap();
                let abs_path = skills_root.join(rel);

                println!("cargo:rerun-if-changed={}", abs_path.display());

                let content = std::fs::read_to_string(&abs_path)
                    .unwrap_or_else(|e| panic!("failed to read {abs_path:?}: {e}"));
                let hash = blake3::hash(content.as_bytes()).to_hex().to_string();

                out.push_str(&format!(
                    "                (\n                    \"{rel}\",\n                    \"{hash}\",\n                    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../predefined/skills/{rel}\")),\n                ),\n"
                ));
            }

            out.push_str("            ],\n");
            out.push_str("        },\n");
        }

        out.push_str("    ]\n");
        out.push_str("}\n");

        let out_dir = std::env::var("OUT_DIR").unwrap();
        let dest = Path::new(&out_dir).join("builtin_skills.rs");
        std::fs::write(&dest, out).unwrap();
    }

    // -------------------------------------------------------------------
    // Plugins
    // -------------------------------------------------------------------
    if let Some(plugins_rel) = builtin["plugins"].as_str() {
        let plugins_root = predefined_root.join("plugins");
        let manifest_path = predefined_root.join(plugins_rel);
        println!("cargo:rerun-if-changed={}", manifest_path.display());
        let plugins_json: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&manifest_path).unwrap())
                .expect("plugins manifest is valid JSON");
        let plugins = plugins_json["plugins"]
            .as_array()
            .expect("plugins manifest has plugins array");

        let mut out = String::new();
        out.push_str(
            "// Auto-generated by build.rs from predefined/plugins/builtin-plugins.json.\n",
        );
        out.push_str("// DO NOT EDIT.\n");
        out.push_str("fn builtin_plugins() -> Vec<BuiltinPlugin> {\n");
        out.push_str("    vec![\n");

        for plugin in plugins {
            let name = plugin["name"].as_str().unwrap();
            out.push_str("        BuiltinPlugin {\n");
            out.push_str(&format!("            name: \"{name}\",\n"));
            out.push_str("            files: vec![\n");

            for file in plugin["files"].as_array().unwrap() {
                let rel = file.as_str().unwrap();
                let abs_path = plugins_root.join(rel);

                println!("cargo:rerun-if-changed={}", abs_path.display());

                let content = std::fs::read_to_string(&abs_path)
                    .unwrap_or_else(|e| panic!("failed to read {abs_path:?}: {e}"));
                let hash = blake3::hash(content.as_bytes()).to_hex().to_string();

                out.push_str(&format!(
                    "                (\n                    \"{rel}\",\n                    \"{hash}\",\n                    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../predefined/plugins/{rel}\")),\n                ),\n"
                ));
            }

            out.push_str("            ],\n");
            out.push_str("        },\n");
        }

        out.push_str("    ]\n");
        out.push_str("}\n");

        let out_dir = std::env::var("OUT_DIR").unwrap();
        let dest = Path::new(&out_dir).join("builtin_plugins.rs");
        std::fs::write(&dest, out).unwrap();
    }

    // -------------------------------------------------------------------
    // Configs
    // -------------------------------------------------------------------
    if let Some(configs) = builtin["configs"].as_array() {
        let mut out = String::new();
        out.push_str(
            "// Auto-generated by build.rs from predefined/builtin.json configs.\n",
        );
        out.push_str("// DO NOT EDIT.\n");
        out.push_str("fn builtin_configs() -> Vec<BuiltinConfig> {\n");
        out.push_str("    vec![\n");

        for entry in configs {
            let rel = entry.as_str().unwrap();
            let abs_path = predefined_root.join(rel);

            println!("cargo:rerun-if-changed={}", abs_path.display());

            let content = std::fs::read_to_string(&abs_path)
                .unwrap_or_else(|e| panic!("failed to read {abs_path:?}: {e}"));
            let hash = blake3::hash(content.as_bytes()).to_hex().to_string();

            out.push_str(&format!(
                "        BuiltinConfig {{\n            rel_path: \"{rel}\",\n            hash: \"{hash}\",\n            content: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../predefined/{rel}\")),\n        }},\n"
            ));
        }

        out.push_str("    ]\n");
        out.push_str("}\n");

        let out_dir = std::env::var("OUT_DIR").unwrap();
        let dest = Path::new(&out_dir).join("builtin_configs.rs");
        std::fs::write(&dest, out).unwrap();
    }
}
