[package]
name = "config"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
kernel = { path = "../core", version = "0.1.0" }
i18n = { path = "../../shared/i18n", version = "0.1.0" }
eval = { path = "../eval", version = "0.1.0" }
idle = { path = "../idle", version = "0.1.0" }
work = { path = "../work", version = "0.1.0" }
study = { path = "../study", version = "0.1.0" }
daily-life = { path = "../daily-life", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9.34"
tracing.workspace = true

[dev-dependencies]
uuid.workspace = true
