[package]
name = "sandbox"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
kernel = { path = "../core", version = "0.1.0" }
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
