[package]
name = "workflow"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
kernel = { path = "../core", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
uuid.workspace = true
xid = "1.1"

[dev-dependencies]
criterion.workspace = true
pipeline = { path = "../pipeline", version = "0.1.0" }
pollster.workspace = true
proptest.workspace = true

[[bench]]
name = "recovery"
harness = false
