// Copyright (c) 2026 13F
// SPDX-License-Identifier: AGPL-3.0

//! Built-in config syncing.
//!
//! Syncs built-in config files (embedded via `include_str!`) from the repo to the
//! user's local `~/.aman/` directory. Tracks content hashes so user modifications
//! are detected and preserved across updates.
//!
//! Shares `~/.aman/.manifest.json` with [`super::skill_sync`] and
//! [`super::plugin_sync`] — config hashes are stored under `hashes.configs`.

use std::collections::HashMap;
use std::path::Path;

use super::skill_sync::{aman_data_dir, load_unified_manifest, save_unified_manifest};

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

/// A single built-in config file embedded in the binary.
struct BuiltinConfig {
    /// Relative path from `predefined/` (e.g. `cards.json`, `agents/code-agents.json`).
    rel_path: &'static str,
    /// Precomputed blake3 hex hash.
    hash: &'static str,
    /// File content.
    content: &'static str,
}

// ---------------------------------------------------------------------------
// Built-in config definitions (auto-generated by build.rs)
// ---------------------------------------------------------------------------

include!(concat!(env!("OUT_DIR"), "/builtin_configs.rs"));

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn content_hash(content: &str) -> String {
    blake3::hash(content.as_bytes()).to_hex().to_string()
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Sync built-in configs to `~/.aman/` (convenience wrapper).
///
/// See [`sync_builtin_configs_to`] for full documentation.
pub fn sync_builtin_configs() -> Result<(), Box<dyn std::error::Error>> {
    sync_builtin_configs_to(&aman_data_dir())
}

/// Sync built-in configs to a given data directory.
///
/// For each built-in config file:
/// - **New** (not in manifest) → created.
/// - **Unmodified** (user copy hash matches manifest) → overwritten with latest.
/// - **Modified** (user changed their copy) → preserved, logged at WARN level.
///
/// The manifest is updated with the *current built-in* hashes so future syncs
/// can correctly detect user modifications.
fn sync_builtin_configs_to(data_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let manifest_path = data_dir.join(".manifest.json");
    let mut manifest = load_unified_manifest(&manifest_path);

    let configs = builtin_configs();
    let mut new_hashes = HashMap::new();

    for cfg in &configs {
        let dest = data_dir.join(cfg.rel_path);

        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }

        let user_modified = manifest
            .hashes
            .configs
            .get(cfg.rel_path)
            .map(|prev_hash| {
                dest.exists()
                    && std::fs::read_to_string(&dest)
                        .ok()
                        .map(|current| content_hash(&current) != *prev_hash)
                        .unwrap_or(false)
            })
            .unwrap_or(false);

        if user_modified {
            tracing::warn!(
                file = cfg.rel_path,
                path = %dest.display(),
                "built-in config file has local modifications — preserving user changes"
            );
            new_hashes.insert(cfg.rel_path.to_owned(), cfg.hash.to_owned());
            continue;
        }

        std::fs::write(&dest, cfg.content)?;
        tracing::info!(
            file = cfg.rel_path,
            path = %dest.display(),
            "synced built-in config file"
        );
        new_hashes.insert(cfg.rel_path.to_owned(), cfg.hash.to_owned());
    }

    manifest.hashes.configs = new_hashes;
    save_unified_manifest(&manifest_path, &manifest)?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_entries_exist() {
        let configs = builtin_configs();
        assert!(!configs.is_empty(), "at least one builtin config");
        for cfg in &configs {
            assert!(!cfg.rel_path.is_empty());
            assert!(!cfg.hash.is_empty());
            assert!(!cfg.content.is_empty());
        }
    }

    #[test]
    fn content_hash_is_deterministic() {
        let a = content_hash("hello");
        let b = content_hash("hello");
        assert_eq!(a, b);
    }

    #[test]
    fn sync_creates_configs() {
        let tmp =
            std::env::temp_dir().join(format!("aman-config-sync-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);

        sync_builtin_configs_to(&tmp).expect("sync should succeed");

        for cfg in builtin_configs() {
            let path = tmp.join(cfg.rel_path);
            assert!(path.exists(), "{} should exist", path.display());
        }

        assert!(tmp.join(".manifest.json").exists());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn sync_preserves_user_modified_config() {
        let tmp = std::env::temp_dir().join(format!(
            "aman-config-sync-preserve-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&tmp);

        let configs = builtin_configs();
        let target = &configs[0];
        let target_path = tmp.join(target.rel_path);

        // First sync
        sync_builtin_configs_to(&tmp).expect("first sync");

        // Modify it
        let modified = target.content.to_owned() + "// user edit\n";
        std::fs::write(&target_path, &modified).expect("write modification");

        // Second sync — should preserve
        sync_builtin_configs_to(&tmp).expect("second sync");
        let after = std::fs::read_to_string(&target_path).unwrap();
        assert_eq!(after, modified, "user modification should be preserved");

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn sync_overwrites_unmodified_config() {
        let tmp = std::env::temp_dir().join(format!(
            "aman-config-sync-overwrite-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&tmp);

        let configs = builtin_configs();
        let target = &configs[0];
        let target_path = tmp.join(target.rel_path);

        // First sync
        sync_builtin_configs_to(&tmp).expect("first sync");
        let first = std::fs::read_to_string(&target_path).unwrap();
        assert_eq!(first, target.content);

        // Second sync — unchanged, should overwrite (no-op since content matches)
        sync_builtin_configs_to(&tmp).expect("second sync");
        let second = std::fs::read_to_string(&target_path).unwrap();
        assert_eq!(second, target.content);

        let _ = std::fs::remove_dir_all(&tmp);
    }
}
