// Copyright (c) 2026 13F
// SPDX-License-Identifier: AGPL-3.0

//! Built-in plugin syncing.
//!
//! Syncs built-in plugins (embedded via `include_str!`) from the repo to the user's
//! local `~/.aman/plugins/` directory. Tracks content hashes so user modifications
//! are detected and preserved across updates.
//!
//! Follows the same pattern as [`super::skill_sync`].

use std::collections::HashMap;
use std::path::Path;

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

/// A single built-in plugin embedded in the binary.
struct BuiltinPlugin {
    /// Display name for logging.
    name: &'static str,
    /// `(rel_path, precomputed_blake3_hex, content)` — one entry per file.
    files: Vec<(&'static str, &'static str, &'static str)>,
}

/// Manifest file at `~/.aman/.plugin-manifest.json`.
#[derive(serde::Serialize, serde::Deserialize)]
struct PluginManifest {
    version: u32,
    /// Map from `rel_path` → blake3 hex hash of the last-synced built-in content.
    hashes: HashMap<String, String>,
}

// ---------------------------------------------------------------------------
// Built-in plugin definitions (auto-generated by build.rs)
// ---------------------------------------------------------------------------

include!(concat!(env!("OUT_DIR"), "/builtin_plugins.rs"));

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn content_hash(content: &str) -> String {
    blake3::hash(content.as_bytes()).to_hex().to_string()
}

fn load_manifest(path: &Path) -> PluginManifest {
    std::fs::read_to_string(path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or(PluginManifest { version: 1, hashes: HashMap::new() })
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Sync built-in plugins to `~/.aman/plugins/` (convenience wrapper).
///
/// See [`sync_builtin_plugins_to`] for full documentation.
pub fn sync_builtin_plugins() -> Result<(), Box<dyn std::error::Error>> {
    sync_builtin_plugins_to(&super::skill_sync::aman_data_dir())
}

/// Sync built-in plugins to a given data directory.
///
/// For each file of each built-in plugin:
/// - **New** (not in manifest) → created.
/// - **Unmodified** (user copy hash matches manifest) → overwritten with latest.
/// - **Modified** (user changed their copy) → preserved, logged at WARN level.
///
/// The manifest is updated with the *current built-in* hashes so future syncs
/// can correctly detect user modifications.
fn sync_builtin_plugins_to(data_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let plugins_dir = data_dir.join("plugins");
    std::fs::create_dir_all(&plugins_dir)?;

    let manifest_path = data_dir.join(".plugin-manifest.json");
    let prev_manifest = load_manifest(&manifest_path);

    let plugins = builtin_plugins();
    let mut new_hashes = HashMap::new();

    for plugin in &plugins {
        for &(rel_path, hash, content) in &plugin.files {
            let dest = plugins_dir.join(rel_path);

            // Ensure parent subdirectory exists.
            if let Some(parent) = dest.parent() {
                std::fs::create_dir_all(parent)?;
            }

            let user_modified = prev_manifest
                .hashes
                .get(rel_path)
                .map(|prev_hash| {
                    dest.exists()
                        && std::fs::read_to_string(&dest)
                            .ok()
                            .map(|current| content_hash(&current) != *prev_hash)
                            .unwrap_or(false)
                })
                .unwrap_or(false);

            if user_modified {
                tracing::warn!(
                    plugin = %plugin.name,
                    file = rel_path,
                    path = %dest.display(),
                    "built-in plugin file has local modifications — preserving user changes"
                );
                new_hashes.insert(rel_path.to_owned(), hash.to_owned());
                continue;
            }

            std::fs::write(&dest, content)?;
            tracing::info!(
                plugin = %plugin.name,
                file = rel_path,
                path = %dest.display(),
                "synced built-in plugin file"
            );
            new_hashes.insert(rel_path.to_owned(), hash.to_owned());
        }
    }

    let manifest = PluginManifest { version: 1, hashes: new_hashes };
    std::fs::write(&manifest_path, serde_json::to_string_pretty(&manifest)?)?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn content_hash_is_deterministic() {
        let a = content_hash("hello");
        let b = content_hash("hello");
        assert_eq!(a, b);
    }

    #[test]
    fn content_hash_differs_for_different_content() {
        let a = content_hash("hello");
        let b = content_hash("world");
        assert_ne!(a, b);
    }

    #[test]
    fn sync_creates_plugins_in_dir() {
        let tmp = std::env::temp_dir().join(format!("aman-plugin-sync-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let plugins_dir = tmp.join("plugins");

        sync_builtin_plugins_to(&tmp).expect("sync_to should succeed");

        // Verify all files exist
        for plugin in builtin_plugins() {
            for &(rel_path, _, _) in &plugin.files {
                let path = plugins_dir.join(rel_path);
                assert!(path.exists(), "{} should exist", path.display());
            }
        }

        // Manifest should exist
        assert!(tmp.join(".plugin-manifest.json").exists());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn sync_preserves_user_modified_plugin() {
        let tmp = std::env::temp_dir().join(format!("aman-plugin-sync-preserve-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let plugins_dir = tmp.join("plugins");

        let plugins = builtin_plugins();
        let target_plugin = &plugins[0];
        let target_file = &target_plugin.files[0];
        let target_path = plugins_dir.join(target_file.0);

        // First sync
        sync_builtin_plugins_to(&tmp).expect("first sync");

        // Modify it
        std::fs::write(&target_path, "# modified by user\n").expect("write modification");
        let modified_content = std::fs::read_to_string(&target_path).unwrap();

        // Second sync — should preserve modification
        sync_builtin_plugins_to(&tmp).expect("second sync");
        let after = std::fs::read_to_string(&target_path).unwrap();
        assert_eq!(after, modified_content, "user modification should be preserved");

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn sync_replaces_plugin_that_was_reverted_to_builtin() {
        let tmp = std::env::temp_dir().join(format!("aman-plugin-sync-revert-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let plugins_dir = tmp.join("plugins");

        let plugins = builtin_plugins();
        let target_plugin = &plugins[0];
        let target_file = &target_plugin.files[0];
        let target_path = plugins_dir.join(target_file.0);

        // First sync creates all plugins
        sync_builtin_plugins_to(&tmp).expect("first sync");

        // Modify it
        std::fs::write(&target_path, "# modified\n").expect("write modification");

        // Second sync preserves modification
        sync_builtin_plugins_to(&tmp).expect("second sync");
        let after = std::fs::read_to_string(&target_path).unwrap();
        assert_eq!(after, "# modified\n", "modification still preserved");

        // Revert by writing the original built-in content
        std::fs::write(&target_path, target_file.2).expect("write reverted content");

        // Third sync: file now matches built-in (user "reverted").
        sync_builtin_plugins_to(&tmp).expect("third sync");

        let _ = std::fs::remove_dir_all(&tmp);
    }
}
