// Copyright (c) 2026 13F
// SPDX-License-Identifier: AGPL-3.0

//! Built-in skill syncing.
//!
//! Syncs built-in skills (embedded via `include_str!`) from the repo to the user's
//! local `~/.aman/skills/` directory. Tracks content hashes so user modifications
//! are detected and preserved across updates.
//!
//! The list of built-in skills is defined in `skills/builtin-skills.json` and
//! compiled into the binary via a build script (build.rs).

use std::collections::HashMap;
use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

/// A single built-in skill embedded in the binary.
struct BuiltinSkill {
    /// Display name for logging.
    name: &'static str,
    /// `(rel_path, precomputed_blake3_hex, content)` — one entry per file.
    files: Vec<(&'static str, &'static str, &'static str)>,
}

/// Manifest file at `~/.aman/.manifest.json`.
#[derive(serde::Serialize, serde::Deserialize)]
struct SkillManifest {
    version: u32,
    /// Map from `rel_path` → blake3 hex hash of the last-synced built-in content.
    hashes: HashMap<String, String>,
}

// ---------------------------------------------------------------------------
// Built-in skill definitions (auto-generated by build.rs)
// ---------------------------------------------------------------------------

include!(concat!(env!("OUT_DIR"), "/builtin_skills.rs"));

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn content_hash(content: &str) -> String {
    blake3::hash(content.as_bytes()).to_hex().to_string()
}

fn load_manifest(path: &Path) -> SkillManifest {
    std::fs::read_to_string(path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or(SkillManifest { version: 1, hashes: HashMap::new() })
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Returns the aman user data directory (`~/.aman`).
pub fn aman_data_dir() -> PathBuf {
    let home = std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .unwrap_or_else(|_| "/tmp".to_owned());
    PathBuf::from(home).join(".aman")
}

/// Sync built-in skills to `~/.aman/skills/` (convenience wrapper).
///
/// See [`sync_builtin_skills_to`] for full documentation.
pub fn sync_builtin_skills() -> Result<(), Box<dyn std::error::Error>> {
    sync_builtin_skills_to(&aman_data_dir())
}

/// Sync built-in skills to a given data directory.
///
/// For each file of each built-in skill:
/// - **New** (not in manifest) → created.
/// - **Unmodified** (user copy hash matches manifest) → overwritten with latest.
/// - **Modified** (user changed their copy) → preserved, logged at WARN level.
///
/// The manifest is updated with the *current built-in* hashes so future syncs
/// can correctly detect user modifications.
fn sync_builtin_skills_to(data_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let skills_dir = data_dir.join("skills");
    std::fs::create_dir_all(&skills_dir)?;

    let manifest_path = data_dir.join(".manifest.json");
    let prev_manifest = load_manifest(&manifest_path);

    let skills = builtin_skills();
    let mut new_hashes = HashMap::new();

    for skill in &skills {
        for &(rel_path, hash, content) in &skill.files {
            let dest = skills_dir.join(rel_path);

            // Ensure parent subdirectory exists.
            if let Some(parent) = dest.parent() {
                std::fs::create_dir_all(parent)?;
            }

            let user_modified = prev_manifest
                .hashes
                .get(rel_path)
                .map(|prev_hash| {
                    dest.exists()
                        && std::fs::read_to_string(&dest)
                            .ok()
                            .map(|current| content_hash(&current) != *prev_hash)
                            .unwrap_or(false)
                })
                .unwrap_or(false);

            if user_modified {
                tracing::warn!(
                    skill = %skill.name,
                    file = rel_path,
                    path = %dest.display(),
                    "built-in skill file has local modifications — preserving user changes"
                );
                new_hashes.insert(rel_path.to_owned(), hash.to_owned());
                continue;
            }

            std::fs::write(&dest, content)?;
            tracing::info!(
                skill = %skill.name,
                file = rel_path,
                path = %dest.display(),
                "synced built-in skill file"
            );
            new_hashes.insert(rel_path.to_owned(), hash.to_owned());
        }
    }

    let manifest = SkillManifest { version: 1, hashes: new_hashes };
    std::fs::write(&manifest_path, serde_json::to_string_pretty(&manifest)?)?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn extract_yaml_frontmatter(content: &str) -> Option<&str> {
        let trimmed = content.trim();
        if trimmed.starts_with("---") {
            let after_first = &trimmed[3..];
            after_first.find("\n---").map(|end| after_first[1..end].trim())
        } else {
            None
        }
    }

    #[test]
    fn content_hash_is_deterministic() {
        let a = content_hash("hello");
        let b = content_hash("hello");
        assert_eq!(a, b);
    }

    #[test]
    fn content_hash_differs_for_different_content() {
        let a = content_hash("hello");
        let b = content_hash("world");
        assert_ne!(a, b);
    }

    #[test]
    fn extract_yaml_frontmatter_works() {
        let md = "---\nname: test\nversion: 1.0\n---\n\n# Body";
        let fm = extract_yaml_frontmatter(md);
        assert_eq!(fm, Some("name: test\nversion: 1.0"));

        // Plain text — no frontmatter.
        assert!(extract_yaml_frontmatter("# Just a heading").is_none());

        // Only opening delimiter.
        assert!(extract_yaml_frontmatter("---\nname: orphan").is_none());
    }

    #[test]
    fn all_builtin_skill_definitions_are_valid() {
        for skill in builtin_skills() {
            for &(rel_path, _, content) in &skill.files {
                if rel_path.ends_with(".yaml") || rel_path.ends_with(".yml") {
                    let doc: serde_yaml::Value = serde_yaml::from_str(content)
                        .unwrap_or_else(|e| panic!("{} ({}) is valid YAML: {e}", skill.name, rel_path));
                    assert!(
                        doc.get("name").is_some(),
                        "{} ({}) has a name field",
                        skill.name,
                        rel_path
                    );
                } else if rel_path.ends_with("SKILL.md") {
                    let frontmatter = extract_yaml_frontmatter(content).unwrap_or_else(|| {
                        panic!("{} ({}): SKILL.md must have YAML frontmatter", skill.name, rel_path)
                    });
                    let doc: serde_yaml::Value = serde_yaml::from_str(frontmatter).unwrap_or_else(|e| {
                        panic!("{} ({}): SKILL.md frontmatter must be valid YAML: {e}", skill.name, rel_path)
                    });
                    assert!(
                        doc.get("name").is_some(),
                        "{} ({}): SKILL.md frontmatter must have a name field",
                        skill.name,
                        rel_path
                    );
                }
                // Non-definition files (.py, .md references, etc.) are skipped.
            }
        }
    }

    #[test]
    fn sync_creates_skills_in_dir() {
        let tmp = std::env::temp_dir().join(format!("aman-skill-sync-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let skills_dir = tmp.join("skills");

        sync_builtin_skills_to(&tmp).expect("sync_to should succeed");

        // Verify all files exist
        for skill in builtin_skills() {
            for &(rel_path, _, _) in &skill.files {
                let path = skills_dir.join(rel_path);
                assert!(path.exists(), "{} should exist", path.display());
            }
        }

        // Manifest should exist
        assert!(tmp.join(".manifest.json").exists());

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn sync_preserves_user_modified_skill() {
        let tmp = std::env::temp_dir().join(format!("aman-skill-sync-preserve-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let skills_dir = tmp.join("skills");

        // Pick an arbitrary .yaml file from the manifest to modify
        let skills = builtin_skills();
        let target_skill = skills.iter().find(|s| {
            s.files.iter().any(|(p, _, _)| p.ends_with(".yaml"))
        }).expect("at least one yaml skill");
        let target_file = target_skill.files.iter().find(|(p, _, _)| p.ends_with(".yaml")).unwrap();
        let target_path = skills_dir.join(target_file.0);

        // First sync
        sync_builtin_skills_to(&tmp).expect("first sync");

        // Modify it
        std::fs::write(&target_path, "name: modified-daze\n").expect("write modification");
        let modified_content = std::fs::read_to_string(&target_path).unwrap();

        // Second sync — should preserve modification
        sync_builtin_skills_to(&tmp).expect("second sync");
        let after = std::fs::read_to_string(&target_path).unwrap();
        assert_eq!(after, modified_content, "user modification should be preserved");

        // Other unmodified skills should still exist
        let other_skill = skills.iter()
            .find(|s| s.name != target_skill.name)
            .expect("at least one other skill");
        let other_path = skills_dir.join(other_skill.files[0].0);
        assert!(other_path.exists(), "unmodified skill should still exist");

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn sync_replaces_skill_that_was_reverted_to_builtin() {
        let tmp = std::env::temp_dir().join(format!("aman-skill-sync-revert-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let skills_dir = tmp.join("skills");

        // Pick an arbitrary .yaml file from the manifest
        let skills = builtin_skills();
        let target_skill = skills.iter().find(|s| {
            s.files.iter().any(|(p, _, _)| p.ends_with(".yaml"))
        }).expect("at least one yaml skill");
        let target_file = target_skill.files.iter().find(|(p, _, _)| p.ends_with(".yaml")).unwrap();
        let target_path = skills_dir.join(target_file.0);

        // First sync creates all skills
        sync_builtin_skills_to(&tmp).expect("first sync");

        // Modify it
        std::fs::write(&target_path, "name: modified-daze\n").expect("write modification");

        // Second sync preserves modification
        sync_builtin_skills_to(&tmp).expect("second sync");
        let after = std::fs::read_to_string(&target_path).unwrap();
        assert_eq!(after, "name: modified-daze\n", "modification still preserved");

        // Revert by writing the original built-in content
        std::fs::write(&target_path, target_file.2).expect("write reverted content");

        // Third sync: file now matches built-in (user "reverted").
        sync_builtin_skills_to(&tmp).expect("third sync");

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn sync_preserves_modified_supporting_file() {
        let tmp = std::env::temp_dir().join(format!(
            "aman-skill-sync-support-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&tmp);
        let skills_dir = tmp.join("skills");

        // Find a skill with multiple files (entry point + supporting files)
        let skills = builtin_skills();
        let multi = skills.iter()
            .find(|s| s.files.len() > 1)
            .expect("at least one multi-file skill");
        let entry = &multi.files[0];
        let supporting = &multi.files[1];
        let supporting_path = skills_dir.join(supporting.0);

        sync_builtin_skills_to(&tmp).expect("first sync");

        // Modify the supporting file
        std::fs::write(&supporting_path, "# modified reference\n").expect("write modification");
        let modified = std::fs::read_to_string(&supporting_path).unwrap();

        // Second sync — should preserve modification
        sync_builtin_skills_to(&tmp).expect("second sync");
        let after = std::fs::read_to_string(&supporting_path).unwrap();
        assert_eq!(after, modified, "user modification to supporting file should be preserved");

        // The entry file (SKILL.md) should still be the original (unmodified = overwritten)
        let entry_path = skills_dir.join(entry.0);
        let on_disk = std::fs::read_to_string(&entry_path).unwrap();
        assert_eq!(on_disk, entry.2, "unmodified entry file should be overwritten with latest");

        let _ = std::fs::remove_dir_all(&tmp);
    }
}
