// Copyright (c) 2026 13F
// SPDX-License-Identifier: AGPL-3.0

//! Build script for the gateway crate.
//!
//! Reads `predefined/builtin.json` as the top-level index, then follows its

// build.rs must use println! for cargo directives (cargo:warning=, cargo:rerun-if-changed=).
// safe_println! is not available in build scripts (no kernel dep).
#![allow(clippy::print_stdout)]
//! `skills` and `plugins` pointers to discover and embed all built-in files
//! via `include_str!()` with pre-computed blake3 hashes.

use std::path::Path;
use std::process::Command;

/// Pre-build steps that must run before the gateway compiles.
/// Each entry is a (command, args, working_dir) tuple.
/// The working_dir is relative to the workspace root.
const PRE_BUILD_STEPS: &[(&str, &[&str], &str)] = &[
    (
        "npm",
        &["run", "build"],
        "shared/frontend/chat-input",
    ),
    (
        "npm",
        &["run", "build"],
        "shared/frontend/agent-selector",
    ),
];

fn run_pre_build_steps(workspace_root: &Path) {
    if PRE_BUILD_STEPS.is_empty() {
        return;
    }
    println!("cargo:warning=Running {} pre-build step(s)...", PRE_BUILD_STEPS.len());
    for (i, (cmd, args, work_dir)) in PRE_BUILD_STEPS.iter().enumerate() {
        let dir = workspace_root.join(work_dir);
        // Re-run build.rs when sources in this component change
        println!("cargo:rerun-if-changed={}", dir.display());
        println!(
            "cargo:warning=[{}/{}] {} {} (in {})",
            i + 1,
            PRE_BUILD_STEPS.len(),
            cmd,
            args.join(" "),
            dir.display(),
        );
        // On Windows, run through `cmd /c`; on Unix, invoke the command
        // directly. Using `cmd` unconditionally would fail with "No such
        // file or directory" on non-Windows platforms.
        let status = if cfg!(windows) {
            Command::new("cmd")
                .args(["/c", cmd])
                .args(*args)
                .current_dir(&dir)
                .status()
        } else {
            Command::new(cmd)
                .args(*args)
                .current_dir(&dir)
                .status()
        }
        .unwrap_or_else(|e| {
            panic!(
                "Failed to run pre-build step [{}/{}]: {} {} — {}",
                i + 1,
                PRE_BUILD_STEPS.len(),
                cmd,
                args.join(" "),
                e,
            )
        });
        if !status.success() {
            panic!(
                "Pre-build step [{}/{}] failed with exit code {:?}: {} {}",
                i + 1,
                PRE_BUILD_STEPS.len(),
                status.code(),
                cmd,
                args.join(" "),
            );
        }
    }
    println!("cargo:warning=All pre-build steps completed.");
}

fn main() {
    let workspace_root = Path::new(&std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../..");
    run_pre_build_steps(&workspace_root);

    // Compile proto definitions for gRPC server stubs.
    tonic_build::compile_protos("../../proto/aman.proto")
        .expect("failed to compile aman.proto");

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let predefined_root = Path::new(&manifest_dir).join("../../predefined");

    // Read the top-level builtin index. All sub-manifest paths are resolved
    // relative to `predefined/`.
    let builtin_path = predefined_root.join("builtin.json");
    println!("cargo:rerun-if-changed={}", builtin_path.display());
    let builtin: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&builtin_path).unwrap())
            .expect("builtin.json is valid JSON");

    // -------------------------------------------------------------------
    // Skills
    // -------------------------------------------------------------------
    if let Some(skills_rel) = builtin["skills"].as_str() {
        let skills_root = predefined_root.join("skills");
        let manifest_path = predefined_root.join(skills_rel);
        println!("cargo:rerun-if-changed={}", manifest_path.display());
        let skills_json: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&manifest_path).unwrap())
                .expect("skills manifest is valid JSON");
        let skills = skills_json["skills"]
            .as_array()
            .expect("skills manifest has skills array");

        let mut out = String::new();
        out.push_str(
            "// Auto-generated by build.rs from predefined/skills/builtin-skills.json.\n",
        );
        out.push_str("// DO NOT EDIT.\n");
        out.push_str("fn builtin_skills() -> Vec<BuiltinSkill> {\n");
        out.push_str("    vec![\n");

        for skill in skills {
            let name = skill["name"].as_str().unwrap();
            out.push_str("        BuiltinSkill {\n");
            out.push_str(&format!("            name: \"{name}\",\n"));
            out.push_str("            files: vec![\n");

            for file in skill["files"].as_array().unwrap() {
                let rel = file.as_str().unwrap();
                let abs_path = skills_root.join(rel);

                println!("cargo:rerun-if-changed={}", abs_path.display());

                let content = std::fs::read_to_string(&abs_path)
                    .unwrap_or_else(|e| panic!("failed to read {abs_path:?}: {e}"));
                let hash = blake3::hash(content.as_bytes()).to_hex().to_string();

                out.push_str(&format!(
                    "                (\n                    \"{rel}\",\n                    \"{hash}\",\n                    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../predefined/skills/{rel}\")),\n                ),\n"
                ));
            }

            out.push_str("            ],\n");
            out.push_str("        },\n");
        }

        out.push_str("    ]\n");
        out.push_str("}\n");

        let out_dir = std::env::var("OUT_DIR").unwrap();
        let dest = Path::new(&out_dir).join("builtin_skills.rs");
        std::fs::write(&dest, out).unwrap();
    }

    // -------------------------------------------------------------------
    // Plugins
    // -------------------------------------------------------------------
    if let Some(plugins_rel) = builtin["plugins"].as_str() {
        let plugins_root = predefined_root.join("plugins");
        let manifest_path = predefined_root.join(plugins_rel);
        println!("cargo:rerun-if-changed={}", manifest_path.display());
        let plugins_json: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&manifest_path).unwrap())
                .expect("plugins manifest is valid JSON");
        let plugins = plugins_json["plugins"]
            .as_array()
            .expect("plugins manifest has plugins array");

        let mut out = String::new();
        out.push_str(
            "// Auto-generated by build.rs from predefined/plugins/builtin-plugins.json.\n",
        );
        out.push_str("// DO NOT EDIT.\n");
        out.push_str("fn builtin_plugins() -> Vec<BuiltinPlugin> {\n");
        out.push_str("    vec![\n");

        for plugin in plugins {
            let name = plugin["name"].as_str().unwrap();
            out.push_str("        BuiltinPlugin {\n");
            out.push_str(&format!("            name: \"{name}\",\n"));
            out.push_str("            files: vec![\n");

            for file in plugin["files"].as_array().unwrap() {
                let rel = file.as_str().unwrap();
                let abs_path = plugins_root.join(rel);

                println!("cargo:rerun-if-changed={}", abs_path.display());

                let content = std::fs::read_to_string(&abs_path)
                    .unwrap_or_else(|e| panic!("failed to read {abs_path:?}: {e}"));
                let hash = blake3::hash(content.as_bytes()).to_hex().to_string();

                out.push_str(&format!(
                    "                (\n                    \"{rel}\",\n                    \"{hash}\",\n                    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../predefined/plugins/{rel}\")),\n                ),\n"
                ));
            }

            out.push_str("            ],\n");
            out.push_str("        },\n");
        }

        out.push_str("    ]\n");
        out.push_str("}\n");

        let out_dir = std::env::var("OUT_DIR").unwrap();
        let dest = Path::new(&out_dir).join("builtin_plugins.rs");
        std::fs::write(&dest, out).unwrap();
    }

    // -------------------------------------------------------------------
    // Self module — read from builtin.json self section
    // -------------------------------------------------------------------
    if let Some(self_cfg) = builtin.get("self") {
        let self_root = predefined_root.join("self");
        let mut out = String::new();
        out.push_str(
            "// Auto-generated by build.rs from predefined/builtin.json self section.\n",
        );
        out.push_str("// DO NOT EDIT.\n");
        out.push_str("fn builtin_self_files() -> Vec<BuiltinSelfFile> {\n");
        out.push_str("    vec![\n");

        // Collect files from self.files and self.modules.*.files
        let mut seen = std::collections::HashSet::new();
        let mut add_file = |rel: &str| {
            if !seen.insert(rel.to_owned()) { return; }
            let abs_path = self_root.join(rel.strip_prefix("self/").unwrap_or(rel));
            println!("cargo:rerun-if-changed={}", abs_path.display());
            let content = std::fs::read_to_string(&abs_path)
                .unwrap_or_else(|e| panic!("failed to read {abs_path:?}: {e}"));
            let hash = blake3::hash(content.as_bytes()).to_hex().to_string();
            out.push_str(&format!(
                "        BuiltinSelfFile {{\n            rel_path: \"{rel}\",\n            hash: \"{hash}\",\n            content: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../predefined/{rel}\")),\n        }},\n"
            ));
        };

        // Top-level files (self/__init__.py, self/config.yaml)
        if let Some(files) = self_cfg["files"].as_array() {
            for f in files { add_file(f.as_str().unwrap()); }
        }
        // bridge.py
        add_file("self/bridge.py");
        // Module files
        if let Some(modules) = self_cfg["modules"].as_object() {
            for (_name, mod_cfg) in modules {
                if let Some(files) = mod_cfg["files"].as_array() {
                    for f in files { add_file(f.as_str().unwrap()); }
                }
            }
        }

        out.push_str("    ]\n");
        out.push_str("}\n");

        let out_dir = std::env::var("OUT_DIR").unwrap();
        let dest = Path::new(&out_dir).join("builtin_self.rs");
        std::fs::write(&dest, out).unwrap();
    }

    // -------------------------------------------------------------------
    // Configs
    // -------------------------------------------------------------------
    if let Some(configs) = builtin["configs"].as_array() {
        let mut out = String::new();
        out.push_str(
            "// Auto-generated by build.rs from predefined/builtin.json configs.\n",
        );
        out.push_str("// DO NOT EDIT.\n");
        out.push_str("fn builtin_configs() -> Vec<BuiltinConfig> {\n");
        out.push_str("    vec![\n");

        for entry in configs {
            let rel = entry.as_str().unwrap();
            let abs_path = predefined_root.join(rel);

            println!("cargo:rerun-if-changed={}", abs_path.display());

            let content = std::fs::read_to_string(&abs_path)
                .unwrap_or_else(|e| panic!("failed to read {abs_path:?}: {e}"));
            let hash = blake3::hash(content.as_bytes()).to_hex().to_string();

            out.push_str(&format!(
                "        BuiltinConfig {{\n            rel_path: \"{rel}\",\n            hash: \"{hash}\",\n            content: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../predefined/{rel}\")),\n        }},\n"
            ));
        }

        out.push_str("    ]\n");
        out.push_str("}\n");

        let out_dir = std::env::var("OUT_DIR").unwrap();
        let dest = Path::new(&out_dir).join("builtin_configs.rs");
        std::fs::write(&dest, out).unwrap();
    }

    // -------------------------------------------------------------------
    // Agents — read from agents.json (referenced by builtin.json)
    // -------------------------------------------------------------------
    if let Some(agents_rel) = builtin["agents"].as_str() {
        let agents_root = predefined_root.join("agents");
        let manifest_path = predefined_root.join(agents_rel);
        println!("cargo:rerun-if-changed={}", manifest_path.display());
        let agents_json: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&manifest_path).unwrap())
                .expect("agents manifest is valid JSON");
        let agents = agents_json["agents"]
            .as_array()
            .expect("agents manifest has agents array");

        let mut out = String::new();
        out.push_str(
            "// Auto-generated by build.rs from predefined/agents/agents.json.\n",
        );
        out.push_str("// DO NOT EDIT.\n");
        out.push_str("fn builtin_agents() -> Vec<BuiltinAgentDef> {\n");
        out.push_str("    vec![\n");

        for agent in agents {
            let key = agent["key"].as_str().unwrap();
            let display_name = agent["display_name"].as_str().unwrap();
            out.push_str("        BuiltinAgentDef {\n");
            out.push_str(&format!("            key: \"{key}\",\n"));
            out.push_str(&format!("            display_name: \"{display_name}\",\n"));
            out.push_str("            files: &[\n");

            for file in agent["files"].as_array().unwrap() {
                let rel = file.as_str().unwrap();
                let abs_path = agents_root.join(
                    rel.strip_prefix("agents/").unwrap_or(rel)
                );

                println!("cargo:rerun-if-changed={}", abs_path.display());

                // Try text first; fall back to binary for non-UTF-8 files
                // (PNG, JPEG, WebP, etc.). This avoids hard-coding a list of
                // binary extensions.
                if let Ok(text) = std::fs::read_to_string(&abs_path) {
                    let hash = blake3::hash(text.as_bytes()).to_hex().to_string();
                    out.push_str(&format!(
                        "                BuiltinAgentFile {{\n                    rel_path: \"{rel}\",\n                    hash: \"{hash}\",\n                    content: BuiltinFileContent::Text(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../predefined/{rel}\"))),\n                }},\n"
                    ));
                } else {
                    let data = std::fs::read(&abs_path)
                        .unwrap_or_else(|e| panic!("failed to read binary {abs_path:?}: {e}"));
                    let hash = blake3::hash(&data).to_hex().to_string();
                    out.push_str(&format!(
                        "                BuiltinAgentFile {{\n                    rel_path: \"{rel}\",\n                    hash: \"{hash}\",\n                    content: BuiltinFileContent::Binary(include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../predefined/{rel}\"))),\n                }},\n"
                    ));
                }
            }

            out.push_str("            ],\n");
            out.push_str("        },\n");
        }

        out.push_str("    ]\n");
        out.push_str("}\n");

        let out_dir = std::env::var("OUT_DIR").unwrap();
        let dest = Path::new(&out_dir).join("builtin_agents.rs");
        std::fs::write(&dest, out).unwrap();
    }

    // -------------------------------------------------------------------
    // Provenance marker
    // -------------------------------------------------------------------
    {
        let proof_path = predefined_root.join("proof.bin");
        println!("cargo:rerun-if-changed={}", proof_path.display());
        let out = "// Aman provenance marker — auto-generated.\n\
             #[used]\n\
             static AMAN_PROOF: &[u8] = include_bytes!(concat!(\
                 env!(\"CARGO_MANIFEST_DIR\"), \
                 \"/../../predefined/proof.bin\"\
             ));\n"
            .to_string();
        let out_dir = std::env::var("OUT_DIR").unwrap();
        let dest = Path::new(&out_dir).join("proof.rs");
        std::fs::write(&dest, out).unwrap();
    }
}
