// Copyright (c) 2026 13F
// SPDX-License-Identifier: AGPL-3.0

//! Layered config merging infrastructure.
//!
//! The [`ConfigPatch`] trait powers the `#[derive(ConfigPatch)]` macro: every
//! config field type participates in merging through its associated `Patch`
//! type. Primitive and external types use a patch of themselves (replace
//! semantics), while nested config structs derive `ConfigPatch` and use a
//! generated `Partial*` type.

use std::collections::{HashMap, HashSet};

/// Trait for types that can be merged with a patch.
///
/// For config structs generated by `#[derive(ConfigPatch)]`, `Patch` is the
/// generated `Partial*` struct and `merge` recurses field-by-field. For
/// primitive/external types, `Patch = Self` and `merge` replaces the value.
pub trait ConfigPatch: Sized {
    type Patch;

    /// Merge a patch into `self`.
    fn merge(&mut self, patch: Self::Patch);

    /// Build a new value from a patch.
    ///
    /// Implementors that have a meaningful default can start from `Default` and
    /// then `merge` the patch.
    fn from_patch(patch: Self::Patch) -> Self;
}

macro_rules! replace_patch {
    ($($ty:ty),* $(,)?) => {
        $(
            impl ConfigPatch for $ty {
                type Patch = Self;
                fn merge(&mut self, patch: Self::Patch) {
                    *self = patch;
                }
                fn from_patch(patch: Self::Patch) -> Self {
                    patch
                }
            }
        )*
    };
}

replace_patch!(
    bool,
    u8, u16, u32, u64, u128, usize,
    i8, i16, i32, i64, i128, isize,
    f32, f64,
    String,
    std::path::PathBuf,
    crate::UiStyle,
    crate::AgentsViewer,
);

impl<T: ConfigPatch> ConfigPatch for Option<T> {
    type Patch = Option<T::Patch>;

    fn merge(&mut self, patch: Self::Patch) {
        if let Some(p) = patch {
            if let Some(inner) = self.as_mut() {
                inner.merge(p);
            } else {
                *self = Some(T::from_patch(p));
            }
        }
    }

    fn from_patch(patch: Self::Patch) -> Self {
        patch.map(T::from_patch)
    }
}

impl<T: ConfigPatch> ConfigPatch for Vec<T> {
    type Patch = Self;

    fn merge(&mut self, patch: Self::Patch) {
        *self = patch;
    }

    fn from_patch(patch: Self::Patch) -> Self {
        patch
    }
}

impl<K, V, S> ConfigPatch for HashMap<K, V, S>
where
    K: std::cmp::Eq + std::hash::Hash,
    S: std::hash::BuildHasher + Default,
{
    type Patch = Self;

    fn merge(&mut self, patch: Self::Patch) {
        *self = patch;
    }

    fn from_patch(patch: Self::Patch) -> Self {
        patch
    }
}

impl<T, S> ConfigPatch for HashSet<T, S>
where
    T: std::cmp::Eq + std::hash::Hash,
    S: std::hash::BuildHasher + Default,
{
    type Patch = Self;

    fn merge(&mut self, patch: Self::Patch) {
        *self = patch;
    }

    fn from_patch(patch: Self::Patch) -> Self {
        patch
    }
}

impl ConfigPatch for serde_json::Value {
    type Patch = Self;
    fn merge(&mut self, patch: Self::Patch) {
        *self = patch;
    }
    fn from_patch(patch: Self::Patch) -> Self {
        patch
    }
}

/// Convenience macro for external config types that should be replaced whole
/// rather than field-merged.
#[macro_export]
macro_rules! replace_config_patch {
    ($($ty:ty),* $(,)?) => {
        $(
            impl $crate::patch::ConfigPatch for $ty {
                type Patch = Self;
                fn merge(&mut self, patch: Self::Patch) {
                    *self = patch;
                }
                fn from_patch(patch: Self::Patch) -> Self {
                    patch
                }
            }
        )*
    };
}

// External subsystem configs are opaque to this crate: patch them by replacing
// the entire value.
replace_config_patch!(
    work::WorkConfig,
    study::StudyConfig,
    daily_life::DailyLifeConfig,
    idle::BoredomConfig,
    i18n::Locale,
);

// Local enums used as config fields are replaced whole.
replace_config_patch!(
    super::BusMode,
    super::SecretsMode,
    super::IdlePersonality,
);

// Simple local structs used as collection elements are replaced whole.
replace_config_patch!(super::WorkflowDefinition);
