[package]
name = "plugin"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
axum = { version = "0.8.6", features = ["multipart"] }
kernel = { path = "../core" }
async-trait.workspace = true
flate2 = "1.1.5"
futures = "0.3.31"
futures-timer = "3.0.3"
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9.34"
tar = "0.4.44"
tokio = { version = "1.48.0", features = ["rt"] }
uuid.workspace = true
wasmtime = "28.0.0"

[dev-dependencies]
pollster.workspace = true
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.5.2", features = ["util"] }
wat = "1.240.0"
