// Copyright (c) 2026 13F
// SPDX-License-Identifier: AGPL-3.0

//! Built-in agent seeding.
//!
//! Seeds predefined agents from `predefined/agents/` into the user's
//! `~/.aman/agents/` data directory on first run (when no agents exist).
//! Does NOT overwrite existing agents.
//!
//! The list of agents and their files is defined in
//! `predefined/agents/agents.json` and embedded at compile time by `build.rs`
//! (see also `predefined/builtin.json`).

use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
// Data types (must match what build.rs generates)
// ---------------------------------------------------------------------------

pub enum BuiltinFileContent {
    Text(&'static str),
    Binary(&'static [u8]),
}

pub struct BuiltinAgentFile {
    pub rel_path: &'static str,
    #[allow(dead_code)]
    pub hash: &'static str,
    pub content: BuiltinFileContent,
}

pub struct BuiltinAgentDef {
    pub key: &'static str,
    pub display_name: &'static str,
    pub files: &'static [BuiltinAgentFile],
}

// ---------------------------------------------------------------------------
// Built-in agent definitions (auto-generated by build.rs)
// ---------------------------------------------------------------------------

include!(concat!(env!("OUT_DIR"), "/builtin_agents.rs"));

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Returns the aman user data directory (`~/.aman`).
pub fn aman_data_dir() -> PathBuf {
    let home = std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .unwrap_or_else(|_| "/tmp".to_owned());
    PathBuf::from(home).join(".aman")
}

fn agents_data_dir() -> PathBuf {
    aman_data_dir().join("agents")
}

/// Count existing agent subdirectories under `~/.aman/agents/`.
fn existing_agent_count(dir: &Path) -> usize {
    if !dir.exists() {
        return 0;
    }
    std::fs::read_dir(dir)
        .map(|entries| {
            entries
                .filter_map(|e| e.ok())
                .filter(|e| e.file_type().is_ok_and(|t| t.is_dir()))
                .count()
        })
        .unwrap_or(0)
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Discover agents that exist on the filesystem but aren't yet in config.yaml.
///
/// This is a bulk check: if config.yaml already has any agents registered, we
/// skip discovery entirely — no per-directory iteration. New agents should be
/// created through the UI (`create_agent`), not by manually copying directories.
///
/// Returns the keys of newly discovered agents (always empty when config already
/// has agents).
pub fn discover_filesystem_agents() -> Vec<String> {
    // If config already has agents registered, skip entirely — no per-agent checking.
    if config_has_agents() {
        tracing::info!("config.yaml already has agents — skipping filesystem discovery");
        return Vec::new();
    }

    // No config yet — seed_builtin_agents handles first-run setup.
    Vec::new()
}

/// Check whether config.yaml already has any agents registered.
fn config_has_agents() -> bool {
    let config_path = aman_data_dir().join("config.yaml");
    if !config_path.exists() {
        return false;
    }
    let raw = match std::fs::read_to_string(&config_path) {
        Ok(s) => s,
        Err(_) => return false,
    };
    let config: serde_yaml::Value = match serde_yaml::from_str(&raw) {
        Ok(v) => v,
        Err(_) => return false,
    };
    config
        .get("agents")
        .and_then(|a| a.as_mapping())
        .is_some_and(|m| !m.is_empty())
}

/// Seed predefined agents into `~/.aman/agents/` if no agents exist yet.
///
/// Checks config.yaml FIRST (primary gate), then the filesystem. If either
/// already has agents, seeding is skipped entirely — no per-agent checking.
///
/// Returns the list of agent keys that were seeded.
pub fn seed_builtin_agents() -> Vec<String> {
    // Primary gate: if config.yaml already has agents registered, skip.
    // This catches cases where the filesystem check might return 0 due to
    // a transient read_dir error or the agents directory not existing yet.
    if config_has_agents() {
        tracing::info!(
            "config.yaml already has agents — skipping seed"
        );
        return Vec::new();
    }

    // Secondary gate: if the agents directory already has subdirectories, skip.
    let agents_dir = agents_data_dir();
    let count = existing_agent_count(&agents_dir);
    if count > 0 {
        tracing::info!(
            existing = count,
            "agents directory already has agents — skipping seed"
        );
        return Vec::new();
    }

    let agents = builtin_agents();
    let mut seeded = Vec::new();

    for agent in &agents {
        let agent_dir = agents_dir.join(agent.key);
        if let Err(e) = seed_one_agent(&agent_dir, agent) {
            tracing::warn!(agent = agent.key, error = %e, "failed to seed agent");
        } else {
            seeded.push(agent.key.to_string());
            tracing::info!(agent = agent.key, "seeded predefined agent");
        }
    }

    // Update config.yaml with the seeded agents.
    if !seeded.is_empty()
        && let Err(e) = update_config_with_agents(&seeded) {
            tracing::warn!(error = %e, "failed to update config.yaml with seeded agents");
        }

    seeded
}

/// Write all embedded files for a single agent to its directory.
///
/// Files are written to `agent_dir` with relative paths preserved from the
/// manifest. Directories are created as needed. Both text and binary content
/// are handled.
///
/// If the agent directory already contains a SOUL.md, the agent is assumed to
/// already exist and seeding is skipped for it — this is the ultimate backstop
/// against overwriting user data.
fn seed_one_agent(agent_dir: &Path, agent: &BuiltinAgentDef) -> Result<(), String> {
    // Ultimate backstop: never overwrite an agent that already has a SOUL.md.
    if agent_dir.join("SOUL.md").exists() {
        tracing::info!(agent = agent.key, path = %agent_dir.display(), "agent already exists — skipping seed for this agent");
        return Ok(());
    }

    // Ensure runtime directories exist (not part of the manifest).
    std::fs::create_dir_all(agent_dir.join("memory"))
        .map_err(|e| format!("create memory dir: {e}"))?;
    std::fs::create_dir_all(agent_dir.join("sessions"))
        .map_err(|e| format!("create sessions dir: {e}"))?;

    // Write each file from the manifest.
    for file in agent.files {
        // Strip the "agents/<key>/" prefix to get the path relative to the
        // agent directory.
        let prefix = format!("agents/{}/", agent.key);
        let rel = file
            .rel_path
            .strip_prefix(&prefix)
            .unwrap_or(file.rel_path);
        let dest = agent_dir.join(rel);

        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("create dir {}: {e}", parent.display()))?;
        }

        // Substitute {name} placeholder for SOUL.md and INTERESTS.md files.
        match &file.content {
            BuiltinFileContent::Text(content) => {
                let content = content.replace("{name}", agent.display_name);
                std::fs::write(&dest, &content)
                    .map_err(|e| format!("write {}: {e}", dest.display()))?;
            }
            BuiltinFileContent::Binary(data) => {
                std::fs::write(&dest, data)
                    .map_err(|e| format!("write {}: {e}", dest.display()))?;
            }
        }
    }

    Ok(())
}

/// Update `config.yaml` to include the seeded agents.
///
/// If the config has no providers, agents are added with empty provider
/// and model strings. The UI handles this gracefully: unconfigured agents
/// are shown but disabled for chat and idle.
fn update_config_with_agents(agent_keys: &[String]) -> Result<(), String> {
    let config_path = aman_data_dir().join("config.yaml");

    // Load existing config or create a minimal default.
    let mut config: serde_yaml::Value = if config_path.exists() {
        let raw = std::fs::read_to_string(&config_path)
            .map_err(|e| format!("read config: {e}"))?;
        serde_yaml::from_str(&raw).unwrap_or(serde_yaml::Value::Mapping(
            serde_yaml::Mapping::new(),
        ))
    } else {
        serde_yaml::Value::Mapping(serde_yaml::Mapping::new())
    };

    // Find the first available provider (or empty string for unconfigured agents).
    let default_provider = config
        .get("providers")
        .and_then(|p| p.as_mapping())
        .and_then(|m| m.keys().next())
        .and_then(|k| k.as_str())
        .map(|s| s.to_string())
        .unwrap_or_default();

    // Build the agents mapping.
    let agents_map = config
        .as_mapping_mut()
        .ok_or("config is not a mapping")?;

    let agents_entry = agents_map
        .entry(serde_yaml::Value::String("agents".to_string()))
        .or_insert_with(|| {
            serde_yaml::Value::Mapping(serde_yaml::Mapping::new())
        });

    let agents = agents_entry
        .as_mapping_mut()
        .ok_or("agents is not a mapping")?;

    // Collect built-in agent definitions for display_name lookup.
    let builtin = builtin_agents();

    for key in agent_keys {
        // Look up display_name from built-in agent definitions.
        let display_name = builtin
            .iter()
            .find(|a| a.key == key.as_str())
            .map(|a| a.display_name)
            .unwrap_or(key.as_str());

        let mut entry = serde_yaml::Mapping::new();
        entry.insert(
            serde_yaml::Value::String("display_name".to_string()),
            serde_yaml::Value::String(display_name.to_string()),
        );
        entry.insert(
            serde_yaml::Value::String("provider".to_string()),
            serde_yaml::Value::String(default_provider.clone()),
        );
        let has_provider = !default_provider.is_empty();
        entry.insert(
            serde_yaml::Value::String("model".to_string()),
            serde_yaml::Value::String(if has_provider { "default" } else { "" }.to_string()),
        );
        // Disable agents without a configured provider so the idle system
        // and chat don't try to use them. The user enables them by configuring.
        entry.insert(
            serde_yaml::Value::String("enabled".to_string()),
            serde_yaml::Value::Bool(has_provider),
        );

        agents.insert(
            serde_yaml::Value::String(key.clone()),
            serde_yaml::Value::Mapping(entry),
        );
    }

    // Write updated config.
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("create config dir: {e}"))?;
    }
    std::fs::write(
        &config_path,
        serde_yaml::to_string(&config).map_err(|e| format!("serialize config: {e}"))?,
    )
    .map_err(|e| format!("write config: {e}"))?;

    tracing::info!(
        path = %config_path.display(),
        "updated config.yaml with seeded agents"
    );
    Ok(())
}
