// Copyright (c) 2026 13F
// SPDX-License-Identifier: AGPL-3.0

//! Built-in self-module syncing.
//!
//! Syncs the Python self-module files (embedded via `include_str!`) from the
//! repo to the user's local `~/.aman/self/` directory. Tracks content hashes
//! so user modifications are detected and preserved across updates.
//!
//! Shares `~/.aman/.manifest.json` with skill, plugin, and config sync —
//! self hashes are stored under `hashes.self`.

use std::collections::HashMap;
use std::path::Path;

use super::skill_sync::{aman_data_dir, load_unified_manifest, save_unified_manifest};

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

struct BuiltinSelfFile {
    rel_path: &'static str,
    hash: &'static str,
    content: &'static str,
}

// ---------------------------------------------------------------------------
// Built-in self file definitions (auto-generated by build.rs)
// ---------------------------------------------------------------------------

include!(concat!(env!("OUT_DIR"), "/builtin_self.rs"));

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Sync built-in self module files to `~/.aman/self/` (convenience wrapper).
pub fn sync_builtin_self() -> Result<(), Box<dyn std::error::Error>> {
    sync_builtin_self_to(&aman_data_dir())
}

/// Sync built-in self module files to a given data directory.
///
/// For each built-in self file:
/// - **New** (not in manifest) → created.
/// - **Unmodified** (user copy hash matches manifest) → overwritten with latest.
/// - **Modified** (user changed their copy) → preserved, logged at WARN level.
fn sync_builtin_self_to(data_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let manifest_path = data_dir.join(".manifest.json");
    let mut manifest = load_unified_manifest(&manifest_path);

    let self_files = builtin_self_files();

    // Ensure hashes.self exists
    let stored_hashes = &mut manifest.hashes.self_files;

    let mut new_hashes: HashMap<String, String> = HashMap::new();

    for file in &self_files {
        let dest = data_dir.join(file.rel_path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }

        let stored = stored_hashes.get(file.rel_path);

        if let Some(stored_hash) = stored {
            // File was synced before — check if user modified it
            if stored_hash == file.hash {
                // Unmodified — overwrite with latest
                std::fs::write(&dest, file.content)?;
                tracing::info!(path = %dest.display(), "self: updated built-in file");
            } else {
                // Hash differs — user may have modified. Check actual content.
                if let Ok(existing) = std::fs::read_to_string(&dest) {
                    let existing_hash = blake3::hash(existing.as_bytes()).to_hex().to_string();
                    if existing_hash == *stored_hash {
                        // User copy matches the old built-in — safe to update
                        std::fs::write(&dest, file.content)?;
                        tracing::info!(path = %dest.display(), "self: updated built-in file");
                    } else {
                        tracing::warn!(
                            path = %dest.display(),
                            "self: preserving user-modified file"
                        );
                        // Keep user's version, but still update the stored hash
                        // so we don't warn again on the next sync
                    }
                } else {
                    // Can't read existing — just overwrite
                    std::fs::write(&dest, file.content)?;
                }
            }
        } else {
            // New file — create it
            std::fs::write(&dest, file.content)?;
            tracing::info!(path = %dest.display(), "self: created new file");
        }

        new_hashes.insert(file.rel_path.to_owned(), file.hash.to_owned());
    }

    *stored_hashes = new_hashes;
    save_unified_manifest(&manifest_path, &manifest)?;
    Ok(())
}
