[package]
name = "persistence"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
kernel = { path = "../core", version = "0.1.0" }
event-bus = { path = "../event-bus", version = "0.1.0" }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
criterion.workspace = true
pollster.workspace = true

[[bench]]
name = "wal_throughput"
harness = false
