[package]
name = "aman-tauri-lib"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
tauri = { version = "2", default-features = false, features = ["macos-private-api", "devtools", "wry", "image-png"] }
tauri-plugin-dialog = "2"
window-vibrancy = "0.7"
rfd = "0.16"
serde.workspace = true
serde_json.workspace = true
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "sync", "time", "process", "net", "io-util"] }
config = { path = "../kernel/config", version = "0.1.0" }
i18n = { path = "../shared/i18n", version = "0.1.0" }
secret = { path = "../kernel/secret", version = "0.1.0" }
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "rustls-tls"] }
futures = "0.3"
tracing.workspace = true
rusqlite = { version = "0.37", features = ["bundled"] }
base64 = "0.22"
rodio = "0.20"

[[bin]]
name = "aman-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", default-features = false, features = [] }
